package com.ipification.mobile.sdk.ip.exception

import com.ipification.mobile.sdk.ip.IPConfiguration

/**
 * Low-level cellular-flow error containing SDK, server, HTTP, and exception details.
 */
class CellularException {

    constructor()

    constructor(exception: Exception) {
        this.exception = exception
    }

    /** HTTP status returned by the API, when available. */
    var httpCode: Int? = null

    /** Error code defined by the SDK. */
    var sdkErrorCode: Int? = 0

    /** Error code returned by the API. */
    var errorCode: String? = null

    /** Error description returned by the API or generated by the SDK. */
    var errorDescription: String? = null

    /** Original exception that caused the failure, when available. */
    var exception: Exception? = null

    /**
     * OAuth `state` of the authorization request that failed, captured when this error is created.
     *
     * Captured here rather than read later because IPConfiguration.currentState is a single shared
     * value that the next IP-channel call resets; null when the channel never set a state.
     */
    var state: String? = IPConfiguration.getInstance().currentState.takeIf(String::isNotBlank)

    /** Returns a readable message containing all available error details. */
    fun getErrorMessage(): String {
        val details = mutableListOf<String>()
        exception?.let {
            details += it::class.java.simpleName
            it.localizedMessage?.takeIf(String::isNotBlank)?.let(details::add)
        }
        errorDescription?.takeIf(String::isNotBlank)?.let(details::add)

        if (details.isEmpty()) {
            details += errorCode ?: "unknown_error $sdkErrorCode"
        }
        httpCode?.let { details += it.toString() }

        return details.joinToString(SEPARATOR)
    }

    /** Converts this internal error into the public SDK error model. */
    fun toIPificationError(): IPificationError = IPificationError(this)

    @Deprecated(
        message = "Use toIPificationError().",
        replaceWith = ReplaceWith("toIPificationError()")
    )
    fun toIPError(): IPificationError = toIPificationError()

    @Deprecated(
        message = "Use getSDKErrorCode().",
        replaceWith = ReplaceWith("getSDKErrorCode()")
    )
    fun getErrorCode(): Int = getSDKErrorCode()

    /** Returns the SDK error code, or -1 when unavailable. */
    fun getSDKErrorCode(): Int = sdkErrorCode ?: -1

    /** Returns the HTTP status code, or -1 when unavailable. */
    fun getHttpStatusCode(): Int = httpCode ?: -1

    private companion object {
        const val SEPARATOR = " - "
    }
}
