package com.ipification.mobile.sdk.ip.exception

/**
 * Public SDK error containing SDK, server, HTTP, channel, and exception details.
 *
 * Legacy OAuth-style fields [error_code] and [error_description] remain available for
 * compatibility. Prefer [serverErrorCode] and [serverDescription] in new Kotlin code.
 */
class IPificationError {

    constructor()

    /** Creates an SDK error caused by [exception]. */
    constructor(exception: Exception) {
        this.exception = exception
    }

    /** Creates a public SDK error from an internal cellular-flow error. */
    internal constructor(error: CellularException) {
        httpCode = error.httpCode
        sdkErrorCode = error.sdkErrorCode
        error_code = error.errorCode
        error_description = error.errorDescription
        exception = error.exception
    }

    /** HTTP status returned by the API, when available. */
    var httpCode: Int? = null

    /** Error code defined by the SDK. */
    var sdkErrorCode: Int? = 0

    /** Error code returned by the API. Retained for OAuth response compatibility. */
    var error_code: String? = null

    /** Error description returned by the API or generated by the SDK. Retained for compatibility. */
    var error_description: String? = null

    /** Authentication channel that produced the error, when available. */
    var channel: String? = null

    /** Original exception that caused the failure, when available. */
    var exception: Exception? = null

    /** Clearer alias for [error_code]. */
    var serverErrorCode: String?
        get() = error_code
        set(value) {
            error_code = value
        }

    /** Clearer alias for [error_description]. */
    var serverDescription: String?
        get() = error_description
        set(value) {
            error_description = value
        }

    /** Returns a readable message containing all available error details. */
    fun getErrorMessage(): String {
        return buildList {
            exception?.localizedMessage?.takeIf(String::isNotBlank)?.let(::add)
            error_description?.takeIf(String::isNotBlank)?.let(::add)

            if (isEmpty()) add(getErrorCode())

            httpCode?.let { add("http=$it") }
            channel?.takeIf(String::isNotBlank)?.let { add("channel=$it") }
        }.distinct().joinToString(SEPARATOR)
    }

    /** Returns the server description, or the complete error message when unavailable. */
    fun getErrorDescription(): String {
        return error_description?.takeIf(String::isNotBlank) ?: getErrorMessage()
    }

    /** Returns the server error code, or the SDK error code as text. */
    fun getErrorCode(): String {
        return error_code?.takeIf(String::isNotBlank)
            ?: sdkErrorCode?.toString()
            ?: UNKNOWN_ERROR
    }

    /** Returns the SDK error code, or -1 when unavailable. */
    fun getSdkErrorCode(): Int = sdkErrorCode ?: UNKNOWN_NUMERIC_CODE

    @Deprecated(
        message = "Use getSdkErrorCode().",
        replaceWith = ReplaceWith("getSdkErrorCode()")
    )
    fun getSDKErrorCode(): Int = getSdkErrorCode()

    @Deprecated(
        message = "Use sdkErrorCode or getSdkErrorCode().",
        replaceWith = ReplaceWith("sdkErrorCode")
    )
    fun getSDKError(): Int? = sdkErrorCode

    /** Returns the HTTP status code, or -1 when unavailable. */
    fun getHttpStatusCode(): Int = httpCode ?: UNKNOWN_NUMERIC_CODE

    @Deprecated("Use getHttpStatusCode().", ReplaceWith("getHttpStatusCode()"))
    fun getResponseStatusCode(): Int = getHttpStatusCode()

    private companion object {
        const val SEPARATOR = " - "
        const val UNKNOWN_ERROR = "unknown_error"
        const val UNKNOWN_NUMERIC_CODE = -1
    }
}
